CREATE TABLE `sppr` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `id_customer` int NOT NULL,
  `no_sppr` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tanggal_sppr` date DEFAULT NULL,
  `nama` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `alamat` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `nik` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `no_telp` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `luas_bangunan` bigint NOT NULL,
  `tahun_bangunan` smallint unsigned DEFAULT NULL,
  `luas_tanah` bigint NOT NULL,
  `blok` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `no` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `harga_jual` bigint NOT NULL,
  `asumsi_plafon_kpr` bigint NOT NULL,
  `biaya_surat_surat` bigint NOT NULL,
  `peningkatan_mutu` bigint NOT NULL,
  `biaya_kelebihan_tanah` bigint DEFAULT NULL,
  `biaya_sudut` bigint DEFAULT NULL,
  `biaya_lain_lain` bigint DEFAULT NULL,
  `total_yang_harus_dibayar` bigint NOT NULL,
  `jumlah_booking_fee` bigint NOT NULL,
  `cicilan_per_bulan` bigint NOT NULL,
  `id_marketing` int DEFAULT NULL,
  `penandatangan` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `keterangan` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `agama` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pekerjaan` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `promo` text COLLATE utf8mb4_unicode_ci,
  `perubahan_posisi` text COLLATE utf8mb4_unicode_ci,
  `keterangan_booking` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nominal_dp` bigint DEFAULT NULL,
  `keterangan_dp` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nominal_biaya_posisi_unit` bigint DEFAULT NULL,
  `keterangan_posisi_unit` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nominal_biaya_kpr` bigint DEFAULT NULL,
  `keterangan_kpr` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nominal_blokir_angsuran` bigint DEFAULT NULL,
  `keterangan_blokir_angsuran` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nominal_biaya_materai` bigint DEFAULT NULL,
  `keterangan_materai` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nominal_biaya_buka_tabungan` bigint DEFAULT NULL,
  `keterangan_tabungan` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `keterangan_shm` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `sppr` (`id`, `id_customer`, `no_sppr`, `tanggal_sppr`, `nama`, `alamat`, `nik`, `no_telp`, `luas_bangunan`, `tahun_bangunan`, `luas_tanah`, `blok`, `no`, `harga_jual`, `asumsi_plafon_kpr`, `biaya_surat_surat`, `peningkatan_mutu`, `biaya_kelebihan_tanah`, `biaya_sudut`, `biaya_lain_lain`, `total_yang_harus_dibayar`, `jumlah_booking_fee`, `cicilan_per_bulan`, `id_marketing`, `penandatangan`, `keterangan`, `created_at`, `updated_at`, `agama`, `pekerjaan`, `promo`, `perubahan_posisi`, `keterangan_booking`, `nominal_dp`, `keterangan_dp`, `nominal_biaya_posisi_unit`, `keterangan_posisi_unit`, `nominal_biaya_kpr`, `keterangan_kpr`, `nominal_blokir_angsuran`, `keterangan_blokir_angsuran`, `nominal_biaya_materai`, `keterangan_materai`, `nominal_biaya_buka_tabungan`, `keterangan_tabungan`, `keterangan_shm`) VALUES ('1', '1', '00/123/2026', '2026-10-02', 'Hendra Dwianta', 'Jl. Kemerdekaan No. 12', '6471052401800007', '02341243234', '45', '2026', '96', '', '', '250000000', '200000000', '0', '0', NULL, NULL, NULL, '56000000', '2000000', '0', '1', 'Henny', 'oke', '2026-10-02 13:24:34', '2026-10-02 13:58:39', NULL, 'Karyawan BUMN', NULL, NULL, NULL, '50000000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
