CREATE TABLE `spr` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_customer` int NOT NULL,
  `id_kavling` int NOT NULL,
  `kode_kavling` varchar(35) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tipe_rumah` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `luas_tanah` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nama_lengkap` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nik` varchar(35) COLLATE utf8mb4_unicode_ci NOT NULL,
  `alamat_rumah` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `no_telp` varchar(35) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nama_keluarga` varchar(75) COLLATE utf8mb4_unicode_ci NOT NULL,
  `hubungan_keluarga` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `no_telp_keluarga` varchar(35) COLLATE utf8mb4_unicode_ci NOT NULL,
  `no_hp_keluarga` varchar(35) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nama_perusahaan` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `alamat_kantor` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `telp_kantor` varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nomor_spr` varchar(35) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tanggal_spr` date NOT NULL,
  `jam_spr` time NOT NULL,
  `harga_rumah` bigint NOT NULL,
  `harga_diskon` int NOT NULL,
  `booking_fee_spr` bigint NOT NULL,
  `nomor_va` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `catatan` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tanggal_akad` date NOT NULL,
  `nomor_akad` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_akad` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `catatan_akad` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tanggal_ppjb` date NOT NULL,
  `nomor_ppjb` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_ppjb` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `catatan_ppjb` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status_spr` int NOT NULL,
  `stt_akad` int NOT NULL,
  `id_marketing` int NOT NULL,
  `nama_marketing` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `stt_keterangan` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
